INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (20060018, 'Moorning-1', 'aaa', 'Y', 3, 'MOORNING');
INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (1, 'OUTER ANCHARAGE', null, 'Y', 1, 'OUTER ANCHARAGE');
INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (2, 'MOORING', null, 'Y', 3, 'MOORNING');
INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (3, 'JETTY-1', null, 'Y', 2, 'JETTY');
INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (4, 'Alfa', 'Alfa', 'y', 1, 'OUTER ANCHARAGE');
INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (20070019, 'JETTY', null, 'Y', 2, 'JETTY');
INSERT INTO MDA.AREA_INFO (ID, NAME, NAME_BN, STATUS, TYPE_ID, TYPE_NAME) VALUES (20060017, 'TEST', 'TEST', 'Y', 3, 'MOORNING');