INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (1, 'A', 'ACTIVE', 'ACTIVE');
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (2, 'I', 'INACTIVE', 'INACTIVE/CANCEL');
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (3, 'R', 'REJECTED', 'REJECTED');
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (4, 'C', 'COMPLETE', 'APPROVED/VERIFY');
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (5, 'P', 'PENDING', 'PENDING');
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (6, 'D', 'DELETE', 'DELETED');