INSERT INTO MDA.VESSELS (ID, NAME, STATUS) VALUES (1, 'MV SIMANTO', 'A');
INSERT INTO MDA.VESSELS (ID, NAME, STATUS) VALUES (2, 'MV LION', 'A');
INSERT INTO MDA.VESSELS (ID, NAME, STATUS) VALUES (3, 'PADMA-BANGLA', 'P');
INSERT INTO MDA.VESSELS (ID, NAME, STATUS) VALUES (20072314001000136, 'MV MARINE', 'A');
INSERT INTO MDA.VESSELS (ID, NAME, STATUS) VALUES (20072313003000134, 'YOUSUF VESSEL', 'P');