INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (1, 'A', 'ACTIVE', null);
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (2, 'I', 'INACTIVE', null);
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (3, 'R', 'REJECTED', null);
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (4, 'C', 'COMPLETE', null);
INSERT INTO MDA.CONFIG_STATUS (ID, TAG, TITLE, OPERATION) VALUES (5, 'P', 'PENDING', null);